setting:
  name: "sanity_test"
  output_root: "./experiments"
  pc_path: "/home/haedam/logs/place_recognition_organized_data/data/Kitti/velodyne_00"
process:
  max_range_m: 60.0
tracker:
  iter_n: 20
eval:
  sensor_cad_path: ./cad/kitti_car.ply